### ISSUE TITLE
POST - Tag

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#18]
# User Story
This does not pertain to the user 

# Acceptance Criteria
- [ ] Create class for posting tags 
- [ ] Build the API 
- [ ] Test the API

# Dependecies
![image](https://github.com/user-attachments/assets/5709ce67-990a-4220-9b7f-9f08ad766cf3)

# Dev Notes
Make sure you ask for help if you are stuck. DO NOT stay stuck for long.

**Comment by Zpcolburn** [comment]
just need to test
