### ISSUE TITLE
GET - All Tags

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#19]
# User Story
No impact to user. 

# Acceptance Criteria
![image](https://github.com/user-attachments/assets/08be4e9a-987e-4b90-95cb-b52c52df54f3)

# Dev Notes

- [ ] Add Tags in the Model folder and create a class.
- [ ] Create the API that returns all tags. 

app.MapGet("customers", () =>
{
    return customers;
});

**Comment by Zpcolburn** [comment]
just need to test
