### ISSUE TITLE
Getting Started - Users

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#20]
# User Story
No direct user impact.

# Acceptance Criteria
![image](https://github.com/user-attachments/assets/a8bbc58d-3b1d-4e6b-b078-c265f71f68ef)

# Dependencies
All other classes are dependent on the User class.

# Dev Notes
- I need to create a Subscription.cs file in the Models folder
- I need to create the Subscription class with the properties listed in the Acceptance Criteria.
![image](https://github.com/user-attachments/assets/2cccb860-fec8-4989-8a4c-e74b0942f253)

**Comment by britnay268** [comment]
Done!
