### ISSUE TITLE
Getting Started - Subscriptions (Follower Id, Author Id)

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#28]
# User Story
No direct user impact.

# Acceptance Criteria
![image](https://github.com/user-attachments/assets/50fe806b-d468-45e4-80f6-d51b92b428fe)

# Dependencies
- This is dependent on the User class.

# Dev Notes
- I need to create a Subscription.cs file in the Models folder
- I need to create the Subscription class with the properties listed in the Acceptance Criteria.
![image](https://github.com/user-attachments/assets/2cccb860-fec8-4989-8a4c-e74b0942f253)

**Comment by britnay268** [comment]
Done!
