### ISSUE TITLE
POST - PostTags

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#33]
# User Story
This does not pertain to the user. 

# Acceptance Criteria
WHEN the API is being tested in Postman/Swagger it should add a new tag to be posted to a article.
THEN once FE is done make sure it works with how back end is built
# Dependecies
![image](https://github.com/user-attachments/assets/4b52ca01-1412-40b5-bea3-f76d56669aa9)

**Comment by Zpcolburn** [comment]
Just need to test
