### ISSUE TITLE
DELETE - PostTags

### ISSUE THREAD

**Issue by FletcherJMoore** [fmings/rare-BE#34]
# User Story
This will allow the FE devs the ability to add a function to delete a tag. (Kinda like Instagram like button).

# Acceptance Criteria
WHEN you test the API in Postman/Swagger you should be able to Delete a Tag.
THEN when the FE builds the code make sure it functions with the API call. 

# Dependecies
This is something similar to what it should like.
![image](https://github.com/user-attachments/assets/b65e4a33-f454-4c9c-afca-cf8baf361cff)

# Dev Notes
![image](https://github.com/user-attachments/assets/31ccd3ba-5a8f-4c2d-9127-67530cc568d7)

**Comment by Zpcolburn** [comment]
just need to test
