### ISSUE TITLE
Getting Started - Mock Data

### ISSUE THREAD

**Issue by fmings** [fmings/rare-BE#40]
# User Story
No direct impact to user.

# Acceptance Criteria
Each teammate will create mock data for their respective models/classes.
There should bee 3-5 pieces of mock data for each class.
Data should represent key-value pairs as detailed in the ERD.

# Dev Notes
ERD Reference: https://drawsql.app/teams/nss-2/diagrams/rare-v1

**Comment by britnay268** [comment]
Done!

**Comment by FletcherJMoore** [comment]
Done!
